# alacritty config

import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

# shell = { program = "/opt/homebrew/bin/tmux", args = ["new"] }

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 10, lines = 10 }
decorations = "Buttonless"
padding = { x = 20, y = 20 }

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 18

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
