#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config auto_balance on

yabai -m config window_placement second_child

yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0

# padding
yabai -m config top_padding 12 
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# mouse settings
#yabai -m config mouse_follows_focus on
#yabai -m config mouse_modifier alt
#yabai -m config mouse_action1 move
#yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Disable specific apps
disabled_apps=(
    "^System Settings$"
    "^Finder$"
    "GIMP"
    "Android Studio"
    "Blender"
    "Fusion"
    )
disabled_titles=(
    "EmulationStation"
    "Accountable2You"
    "Bartender 5"
    "copytype"
    "facsim"
    )

for app in "${disabled_apps[@]}"; do
    yabai -m rule --add app="${app}" manage=off
done

for title in "${disabled_titles[@]}"; do
    yabai -m rule --add title="${title}" manage=off
done
